if ([WestJet_Site] == 'SA360')
	return 'Search'

if ([WestJet_Market_Cleaned] == 'AB')  return 'Alberta'
if ([WestJet_Market_Cleaned] == 'ATL')  return 'Atlantic Canada'
if ([WestJet_Market_Cleaned] == 'BC')  return 'British Columbia'
if ([WestJet_Market_Cleaned] == 'YYC')  return 'Calgary, AB'
if ([WestJet_Market_Cleaned] == 'CAN')  return 'Canada'
if ([WestJet_Market_Cleaned] == 'CT')  return 'City Targeted'
if ([WestJet_Market_Cleaned] == 'YEG')  return 'Edmonton, AB'
if ([WestJet_Market_Cleaned] == 'GCA')  return 'Greater Calgary Area'
if ([WestJet_Market_Cleaned] == 'GEA')  return 'Greater Edmonton Area'
if ([WestJet_Market_Cleaned] == 'GMA')  return 'Greater Montreal Area'
if ([WestJet_Market_Cleaned] == 'GTA')  return 'Greater Toronto Area'
if ([WestJet_Market_Cleaned] == 'GVA')  return 'Greater Vancouver Area'
if ([WestJet_Market_Cleaned] == 'YLW')  return 'Kelowna, BC'
if ([WestJet_Market_Cleaned] == 'MN')  return 'Manitoba'
if ([WestJet_Market_Cleaned] == 'NB')  return 'New Brunswick'
if ([WestJet_Market_Cleaned] == 'NFLD')  return 'Newfoundland'
if ([WestJet_Market_Cleaned] == 'NWT')  return 'Northwest Territories'
if ([WestJet_Market_Cleaned] == 'NS')  return 'Nova Scotia'
if ([WestJet_Market_Cleaned] == 'NU')  return 'Nunavut'
if ([WestJet_Market_Cleaned] == 'ON')  return 'Ontario'
if ([WestJet_Market_Cleaned] == 'GEO')  return 'Other'
if ([WestJet_Market_Cleaned] == 'YOW')  return 'Ottawa, ON'
if ([WestJet_Market_Cleaned] == 'PRA')  return 'Prairies'
if ([WestJet_Market_Cleaned] == 'PEI')  return 'Prince Edward Island'
if ([WestJet_Market_Cleaned] == 'QC')  return 'Quebec'
if ([WestJet_Market_Cleaned] == 'SA')  return 'Saskatchewan'
if ([WestJet_Market_Cleaned] == 'YXE')  return 'Saskatoon, SK'
if ([WestJet_Market_Cleaned] == 'YYT')  return 'St. Johns, NL'
if ([WestJet_Market_Cleaned] == 'YYZ')  return 'Toronto, ON'
if ([WestJet_Market_Cleaned] == 'YVR')  return 'Vancouver, BC'
if ([WestJet_Market_Cleaned] == 'YYJ')  return 'Victoria, BC'
if ([WestJet_Market_Cleaned] == 'WC')  return 'Western Canada'
if ([WestJet_Market_Cleaned] == 'YWG')  return 'Winnipeg, MB'
if ([WestJet_Market_Cleaned] == 'YTT')  return 'Yukon Territories'

return '"' + [WestJet_Market_Cleaned] + '"' + ' | S: ' + [WestJet_Source] + ' | P: ' + [Media_Buy_Name]
