if ([WestJet_Site] == 'SA360') 
	return 'Match Type: ' + [Search_Keyword_Match_Type]


if ([WestJet_Targeting_Cleaned] == 'AVR')  return 'Ad View Retargeting'
if ([WestJet_Targeting_Cleaned] == 'AFT')  return 'Affinity Targeting'
if ([WestJet_Targeting_Cleaned] == 'BHV')  return 'Behavioral Targeting'
if ([WestJet_Targeting_Cleaned] == 'CST')  return 'Category Sponsorship Targeting'
if ([WestJet_Targeting_Cleaned] == 'CHT')  return 'Channel Targeting'
if ([WestJet_Targeting_Cleaned] == 'CDMP')  return 'Client DMP'
if ([WestJet_Targeting_Cleaned] == 'CQT')  return 'Conquesting Targeting'
if ([WestJet_Targeting_Cleaned] == 'CNT')  return 'Content Targeting'
if ([WestJet_Targeting_Cleaned] == 'CXT')  return 'Contextual Targeting'
if ([WestJet_Targeting_Cleaned] == 'CA1P')  return 'Custom Audience 1P Targeting'
if ([WestJet_Targeting_Cleaned] == 'DPT')  return 'Daypart Targeting'
if ([WestJet_Targeting_Cleaned] == 'DMT')  return 'Demographic Targeting'
if ([WestJet_Targeting_Cleaned] == 'ERT')  return 'Engagement Retargeting'
if ([WestJet_Targeting_Cleaned] == 'ECT')  return 'Existing Customers Targeting'
if ([WestJet_Targeting_Cleaned] == 'GNT')  return 'General Targeting'
if ([WestJet_Targeting_Cleaned] == 'GGT')  return 'Geographic Targeting'
if ([WestJet_Targeting_Cleaned] == 'HPT')  return 'Homepage Targeting'
if ([WestJet_Targeting_Cleaned] == 'HLT')  return 'Hyper Local Targeting'
if ([WestJet_Targeting_Cleaned] == 'INM')  return 'In-Market'
if ([WestJet_Targeting_Cleaned] == 'ITT')  return 'Interest Targeting'
if ([WestJet_Targeting_Cleaned] == 'KCT')  return 'Keyword Contextual Targeting'
if ([WestJet_Targeting_Cleaned] == 'LGT')  return 'Language Targeting'
if ([WestJet_Targeting_Cleaned] == 'LAL')  return 'Lookalike Targeting'
if ([WestJet_Targeting_Cleaned] == 'MUL')  return 'Multiple Targeting Methods'
if ([WestJet_Targeting_Cleaned] == 'PWG')  return 'Predefined-Walled Garden'
if ([WestJet_Targeting_Cleaned] == 'PG')   return 'Programmatic Guaranteed'
if ([WestJet_Targeting_Cleaned] == 'PBT')  return 'Purchase Based Targeting'
if ([WestJet_Targeting_Cleaned] == 'RMT')  return 'Re-message Targeting'
if ([WestJet_Targeting_Cleaned] == 'RTT')  return 'Retargeting Targeting'
if ([WestJet_Targeting_Cleaned] == 'RME')  return 'Rich Media Enagers (RM)'
if ([WestJet_Targeting_Cleaned] == 'ROC')  return 'Run of Channel Targeting'
if ([WestJet_Targeting_Cleaned] == 'RON')  return 'Run of Network Targeting'
if ([WestJet_Targeting_Cleaned] == 'ROS')  return 'Run of Site Targeting'
if ([WestJet_Targeting_Cleaned] == 'SRT')  return 'Search Retargeting'
if ([WestJet_Targeting_Cleaned] == 'SCA')  return 'Semantic Custom Audience (Semasio)'
if ([WestJet_Targeting_Cleaned] == 'SCT')  return 'Social Trigger'
if ([WestJet_Targeting_Cleaned] == 'SIT')  return 'Specific Site List'
if ([WestJet_Targeting_Cleaned] == 'TTG')  return 'Topic Targeting'
if ([WestJet_Targeting_Cleaned] == 'TVG')  return 'TV Targeting'
if ([WestJet_Targeting_Cleaned] == 'VVR')  return 'Video View Retargeting'
if ([WestJet_Targeting_Cleaned] == 'WTT')  return 'Weather Trigger Targeting'
if ([WestJet_Targeting_Cleaned] == 'WRT')  return 'Website Retargeting'
if ([WestJet_Targeting_Cleaned] == 'YTP')  return 'YouTube Premium or (VBSN - Virtual Brand Safe Network'
if ([WestJet_Targeting_Cleaned] == 'NA')   return 'NA'

return '"' + [WestJet_Targeting_Cleaned] + '"' + ' | S: ' + [WestJet_Source] + ' | P: ' + [Media_Buy_Name]
